export const TOGGLE_USER_TYPE = 'TOGGLE_USER_TYPE';
export const ADD_LISTING_LOCATION = 'ADD_LISTING_LOCATION';
export const ADD_LISTING_SPACE_DETAILS = 'ADD_LISTING_SPACE_DETAILS';
export const ADD_LISTING_SPACE_AVAILABLE = 'ADD_LISTING_SPACE_AVAILABLE';
export const SET_LISTING_PRICING_TYPE_AND_RATE =
  'SET_LISTING_PRICING_TYPE_AND_RATE';
// export const SET_LISTING_PRICING_RATE = 'SET_LISTING_PRICING_RATE';
// export const SAVE_SPACE_DETAILS = 'SAVE_SPACE_DETAILS';
export const ADD_LISTING = 'ADD_LISTING';
